name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ] # Perbaikan: biasanya ke main, bukan pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4 # Update ke v4 yang lebih stabil
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Jar
      # Menggunakan jar atau shadowJar agar file terkumpul di build/libs
      run: ./gradlew jar 

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ExtraUtilities-Build
        # Menggunakan wildcard (*) agar file tetap ketemu meskipun namanya beda sedikit
        path: build/libs/*.jar
